### ISSUE TITLE
No interactivity on mobile when clicking/touching the "left hand pane"

### ISSUE THREAD

**Issue by justindonnaruma** [bullet-train-pro/bullet_train-conversations#24]
On mobile views, the "left hand pane" doesn't function properly.

When attempting to touch the double arrow to bring out the pane in order to select a conversation, the "touch" does nothing. Using a responsive view with Edge or Safari also doesn't trigger an interaction to bring out the "Pane". There isn't any indication of issue in the console. 

![image](https://github.com/user-attachments/assets/4c0c7ffa-4f5d-4f59-ad43-8bd72fb6aabc)

**Comment by gazayas** [comment]
Found a couple of things here.
1. The button triggers a [stimulus controller action](https://github.com/bullet-train-pro/bullet_train-conversations/blob/a94d1e4c80643876f810023ccadb21175b81c6ba/app/views/account/conversations/subscriptions/index.html.erb#L47-L50) from a third party library, [tailwind-stimulus-components](https://github.com/excid3/tailwindcss-stimulus-components). We don't have that installed in the starter repository, so it should be installed there first.
2. The functionality here is outdated and doesn't work anymore. We should be using the syntax laid out [here](https://github.com/excid3/tailwindcss-stimulus-components/blob/main/docs/slideover.md) in the documentation. I was able to get a side panel to work by using, for instance, `data-slideover-target="dialog"`, `data-slideover-action="slideover#open"`, etc.
3. It looks like there are two instances of slideovers within the same `data-controller="slideover"` `div`, so I think we should check if both are compatible in the same `div` or if we should separate them.

cc @jagthedrummer

**Comment by jagthedrummer** [comment]
I'm not sure we want to install that library directly in the starter repo since it's only used by the conversations gem.

Maybe we should update the installation instructions for this gem to note that you need to install it yourself and do whatever setup steps are needed.

But we should update this gem to use the right attributes to make things happen as expected once you've installed the additional package.

Does that sound reasonable to you @gazayas?

**Comment by jagthedrummer** [comment]
Also, @gazayas, could you open a PR for whatever you did to get things working? I've been messing with it but haven't gotten anything to work. I'm not sure what I'm missing...

**Comment by jagthedrummer** [comment]
Never mind about the PR, @gazayas. I think I got it figured out. Would be interested to hear your thoughts on this PR though. https://github.com/bullet-train-pro/bullet_train-conversations/pull/27
